plugins:
  - jest
  - babel
env:
  es6: true
  node: true
  jest: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  # - 'plugin:flowtype/recommended'
  - 'plugin:lodash-fp/recommended'

parser: babel-eslint

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
